import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import AboutMeSection from '../components/AboutMeSection'
import Contact from '../components/Contact'
import Header from '../components/Header'
import { JobsSection } from '../components/JobsSection'
import MainSection from '../components/MainSection'
import ProjectsSection from '../components/ProjectsSection'
import { SocialItems } from '../components/socialItems'
import Body from './styles'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>LA | Portfolio</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <Body>
        <Header />
        <div className="SectionContent">
          <MainSection />
          <div id="about">
            <AboutMeSection />
          </div>
          <div id="jobs">
            <JobsSection />
          </div>
          <div id="projects">
            <ProjectsSection />
          </div>
          <div id="contact">
            <Contact />
          </div>
        </div>

        <SocialItems />
      </Body>
    </>
  )
}

export default Home
