import type { NextPage } from 'next'
import Head from 'next/head'
import AboutMeSection from '../components/AboutMeSection'
import Header from '../components/Header'
import MainSection from '../components/MainSection'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <MainSection />
      <AboutMeSection/>
    </>
  )
}

export default Home
